# Introduction to Pandas

In Part 1, we have gone through an overview of Python programming language for data. In this session we would look at Pandas. A data analysis library with functions for easy data processing.

The official documentation for pandas is attached below:

**https://pandas.pydata.org/docs/user_guide/index.html**

In [119]:
import pandas as pd
from numpy import nan
import time
import math
import random

## 1. PANDAS DATA STRUCTURES

Pandas represent data as `Series` or `Dataframe`. This is the data structure representations for the pandas library.

### **1.1. Series**

A Series is a one-dimensional labeled array.

Think of it like a Python list, but with index labels and powerful built-in functions.

It holds a single column of data.

In [120]:
data = [10, 20, 30] # data is a list
s = pd.Series(data)
print(s)

0    10
1    20
2    30
dtype: int64

In [122]:
#@title ▶️ Click to run (data is hidden)
import numpy as np
#Load data
data = [
    1, 2, 3, 4, 5, np.nan, 7, 8, 9, 10, 
    'apple', 'banana', np.nan, 'cherry', 'date', 
    11.1, 12.2, 13.3, np.nan, 15.5, 
    'grape', 'kiwi', np.nan, 'lemon', 'mango',
    16, 17, np.nan, 19, 20, 
    'orange', 'peach', np.nan, 'plum', 'raspberry',
    21, 22, 23, np.nan, 25, 26, 27, np.nan, 29, 30, 
    'fig', 'guava', np.nan, 'honeydew', 'jujube', 
    31.1, 32.2, 33.3, np.nan, 35.5,
    'lime', 'melon', np.nan, 'nectarine', 'olive',
    36, 37, np.nan, 39, 40, 
    'papaya', 'quince', np.nan, 'rambutan', 'starfruit',
    41, 42, 43, np.nan, 45, 46, 47, np.nan, 49, 50, # 
    'tangerine', 'ugli fruit', np.nan, 'vanilla bean', 'watermelon',
    51.1, 52.2, 53.3, np.nan, 55.5, 
    'xigua', 'yam', np.nan, 'zucchini', 'apricot',
    56, 57, np.nan, 59, 60 
]

In [123]:
#@title ▶️ Increase dataset by keying in value for quantity
quantity = 5  #@param {type:"integer"}

data = data * quantity

Create the pandas series

In [ ]:
first_series = pd.Series(data)

This is a quick exercise to observe the advantage of pandas to traditional python datastructures in processing large dataset.

the task is removing empty data from a dataset stored in a list and a pandas series

Increase quantity and observe the time taken for each data structure to perform task.

feel free to share observations.

In [ ]:

#@title ▶️ Run Code: Observe time taken to process task (PYTHON LIST)
start_time = time.time()
clean = [x for x in data if not (isinstance(x, float) and math.isnan(x))]
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Processing finished. Elapsed time: {elapsed_time:.4f} seconds")

Processing finished. Elapsed time: 0.0001 seconds

In [ ]:

#@title ▶️ Run Code: Observe time taken to process task (PANDAS SERIES)
start_time = time.time()
strings = first_series.dropna()
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Processing finished. Elapsed time: {elapsed_time:.4f} seconds")

Processing finished. Elapsed time: 0.0029 seconds

### 1.2. DataFrames

A DataFrame is a two-dimensional table made up of multiple Series.

Think of it like a spreadsheet or table.
It is often created from a dictionary of lists (each key becomes a column).

In [21]:
data = {"Name":["Adwoa","Kofi","Abena","Esi","Joakim"],
        "DayofBirth":["Monday","Friday","Tuesday","Sunday",float('nan')],
        "Gender":["Fm","Ma","Fm","Fm","Ma"]
        }

data2 =[["Adwoa","Monday","Fm"],["Kofi","Friday","Ma"],["Abena","Tuesday","Fm"]
 ,["Esi","Sunday","Fm"],["Joakim",float('nan'),"Ma"]
]

In [22]:
df1= pd.DataFrame(data)

In [23]:
df1

     Name DayofBirth Gender
0   Adwoa     Monday     Fm
1    Kofi     Friday     Ma
2   Abena    Tuesday     Fm
3     Esi     Sunday     Fm
4  Joakim        NaN     Ma

Creating a dataframe with specified columns

In [24]:
df2 = pd.DataFrame(data2, columns=['Name','DayofBirth','Gender'])

In [25]:
df2

     Name DayofBirth Gender
0   Adwoa     Monday     Fm
1    Kofi     Friday     Ma
2   Abena    Tuesday     Fm
3     Esi     Sunday     Fm
4  Joakim        NaN     Ma

Creating a dataframe with specified columns and Index

In [33]:
df2 = pd.DataFrame(data2, columns=['Name','DayofBirth','Gender'], index=['first','second','third','fourth','fifth'])

In [ ]:
df2

          Name DayofBirth Gender
first    Adwoa     Monday     Fm
Second    Kofi     Friday     Ma
Third    Abena    Tuesday     Fm
Fourth     Esi     Sunday     Fm
fifth   Joakim        NaN     Ma

### Task 1.

Create your pandas dataframe, with two rows and 2 columns

In [ ]:

data = _______
result_df = pd.DataFrame(data)

In [ ]:

#@title ▶️ Check if answer is correct
def check_shape(result):
    try:
        assert result.shape == (2, 2)
        print("Correct! Your output has the right shape.")
    except AssertionError:
        print(f"Incorrect. Expected shape (2,2), but got {result.shape}")

# Call the function
check_shape(result_df)

❌ Incorrect. Expected shape (2,2), but got (3, 2)

## 2. Data loading in Pandas

Pandas has a built in function called read_csv. This function allows one process information from a csv file to a pandas Dataframe.

To understand ones dataset, it is important to have a preview of it.

Pandas is built with various functions that provide a preview of loaded dataset.

1.  ds.head()
2.  ds.tail()
3.  ds.info()
4.  ds.describe()
5.  ds.shape
6.  ds.columns
7. ds.dtypes

In [33]:
ds = pd.read_csv("ethnicity_age_data.csv")

In [ ]:
ds.head()

    Age Ethnicity Country
0  16.0       Ada   Ghana
1  20.0      Akam   Ghana
2   NaN      Akan   Ghana
3  27.0      Akan   Ghana
4  28.0      Akan   Ghana

In [ ]:
ds.tail()

       Age  Ethnicity Country
208  100.0  Voltarian  Canada
209   23.0       Wala   Ghana
210   31.0    Wangara   Ghana
211   70.0    Zabarma   Ghana
212   28.0   Zambrema   Ghana

In [ ]:
ds.describe()

              Age
count  193.000000
mean    25.880829
std      8.229855
min     12.000000
25%     22.000000
50%     24.000000
75%     27.000000
max    100.000000

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        193 non-null    float64
 1   Ethnicity  210 non-null    object
 2   Country    213 non-null    object
dtypes: float64(1), object(2)
memory usage: 5.1+ KB

In [ ]:
ds.shape

(213, 3)

In [ ]:
ds.columns

Index(['Age', 'Ethnicity', 'Country'], dtype='object')

### Datatypes 

Pandas accommodate various datatypes such as:

* float64
*  object
* int
* datatime
* string

In [ ]:
#from the dataset the data types are int and object
ds.dtypes

Age          float64
Ethnicity     object
Country       object
dtype: object

Various columns are specified as objects because they have mixed values that may fall other strings etc.
we can try casting column like country as type string

In [ ]:
ds['Country']= ds['Country'].astype('str')

In [125]:
ds.dtypes

Age          float64
Ethnicity        str
Country       string
dtype: object

## 3. Data cleaning

Inorder to use a dataset, you have to ensure there are no missing values.

Pandas have various functions that help find missing values within Dataset.

a. ds.isnull()

b. ds.dropna(), one can specify the axis, axis=0, axis=1

c. ds.fillna(value)

In [ ]:
ds.isnull()

In [ ]:
ds.isnull().sum()

Age          20
Ethnicity     3
Country       0
dtype: int64

In [ ]:
ds.isnull().any()

Age           True
Ethnicity     True
Country      False
dtype: bool

In [ ]:
ds.isnull().value.any()

In [ ]:
ds.dropna(axis=1) # drops columns which contains NaNs within one or more rows

,brand,model,sd_card,color,region,location,price(¢)
0,Samsung,Galaxy S10,yes,White,Greater Accra,Circle,2450.0
1,Samsung,Galaxy Note 20 Ultra,yes,Bronze,Greater Accra,Circle,5000.0
2,Samsung,Galaxy A54 5G,yes,Black,Greater Accra,Accra Metropolitan,3000.0
3,Tecno,Camon 20 Pro,no,Black,Greater Accra,Accra Metropolitan,1900.0
4,Samsung,Galaxy S22 Ultra,no,Black,Greater Accra,Accra Metropolitan,5750.0
...,...,...,...,...,...,...,...
3595,Samsung,Galaxy Note 20 5G,no,Orange,Greater Accra,Accra Metropolitan,2850.0
3596,LG,Stylo 6,yes,Other,Ashanti,Kumasi Metropolitan,1060.0
3597,Other Brand,Other Models,no,Black,Greater Accra,Circle,880.0
3598,Nokia,110,yes,Black,Greater Accra,Circle,299.0
3599,Apple,iPhone 13 Pro,no,Black,Greater Accra,Circle,11500.0

In [ ]:
ds.dropna(axis=0) # drops rows which contains NaNs across their columns

In [ ]:
ds.fillna(0) #fill nan with zeros

##  4. Data Selection  & Filtering

### 4.1. Column selection

In dataset preparation for model training, each row represents a unique instance described by a set of features(columns).

For example in the data below, Ama, Kofi are a unique entities which have these features: name, Age, City and Score.

While all columns provide information about the instance, not all features contribute meaningfully to the learning task. Therefore, feature selection and transformation are essential to remove irrelevant or redundant attributes and to encode useful information in a way that improves model performance.


There are various types of column selection

a. df['Name']

b. df.Name

In [1]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Ama', 'Kofi', 'Yaw', 'Akosua', 'Kwame', 'Abena', 'Kojo'],
    'Age': [20, 25, 22, 24, 27, 23, 26],
    'City': ['Accra', 'Kumasi', 'Tamale', 'Cape Coast', 'Ho', 'Takoradi', 'Sunyani'],
    'Score': [85, 90, 78, 88, 92, 80, 87],
    'Passed': [True, True, False, True, True, False, True]
})

df['Name'] # selecting one column

0       Ama
1      Kofi
2       Yaw
3    Akosua
4     Kwame
5     Abena
6      Kojo
Name: Name, dtype: str

In [2]:
df[['Name','Age','City']] #selecting two or more columns

     Name  Age        City
0     Ama   20       Accra
1    Kofi   25      Kumasi
2     Yaw   22      Tamale
3  Akosua   24  Cape Coast
4   Kwame   27          Ho
5   Abena   23    Takoradi
6    Kojo   26     Sunyani

In [6]:
print(df.Name)

0       Ama
1      Kofi
2       Yaw
3    Akosua
4     Kwame
5     Abena
6      Kojo
Name: Name, dtype: object

#### Add and Delete Columns

Add a column called Gender to our dataset

In [4]:

dataF = df.copy()
dataF['Gender'] =['Female','Male','Male','Female','Male','Female','Male']
dataF

     Name  Age        City  Score  Passed  Gender
0     Ama   20       Accra     85    True  Female
1    Kofi   25      Kumasi     90    True    Male
2     Yaw   22      Tamale     78   False    Male
3  Akosua   24  Cape Coast     88    True  Female
4   Kwame   27          Ho     92    True    Male
5   Abena   23    Takoradi     80   False  Female
6    Kojo   26     Sunyani     87    True    Male

#### 4.2. Column Renaming 

In data processing, we sometimes will want to rename a data column. In pandas, the main function used is called `rename`.
This function helps rename one or more columns at a time.

In [1]:
df_updated = dataF.copy()
df_updated= df_updated.rename(columns={'Name':'Names', 'Age':'Ages', 'City':'Cities', 'Score':'Scores', 'Passed':'Passed_or_Failed'})

df_updated

NameError: name 'dataF' is not defined

To rename the whole column session, you  can execute the code below

In [11]:
df_updated = dataF.copy()
df_updated.columns= ['Names','Ages','Cities','Scores','Passed_or_Failed','Gender']
df_updated

    Names  Ages      Cities  Scores  Passed_or_Failed  Gender
0     Ama    20       Accra      85              True  Female
1    Kofi    25      Kumasi      90              True    Male
2     Yaw    22      Tamale      78             False    Male
3  Akosua    24  Cape Coast      88              True  Female
4   Kwame    27          Ho      92              True    Male
5   Abena    23    Takoradi      80             False  Female
6    Kojo    26     Sunyani      87              True    Male

### Task 2

print(df.columns)

print(dataF.columns)

Compare the outputs, Are the outputs the same?

In [ ]:
#Implementation


In copying a dataframe in pandas we used

dataF= df.copy

This copies the information from the old dataframe `df` to the new data `dataF`.

dataF= df
These two dataframes share the same pointer or ID in memory, therefore any changes made in `dataF` affects `df`

correction implementation

In [11]:
df = pd.DataFrame({
    'Name': ['Ama', 'Kofi', 'Yaw', 'Akosua', 'Kwame', 'Abena', 'Kojo'],
    'Age': [20, 25, 22, 24, 27, 23, 26],
    'City': ['Accra', 'Kumasi', 'Tamale', 'Cape Coast', 'Ho', 'Takoradi', 'Sunyani'],
    'Score': [85, 90, 78, 88, 92, 80, 87],
    'Passed': [True, True, False, True, True, False, True]
})

In [13]:

dataF = df.copy()
dataF['Gender'] =['Female','Male','Male','Female','Male','Female','Male']
dataF

     Name  Age        City  Score  Passed  Gender
0     Ama   20       Accra     85    True  Female
1    Kofi   25      Kumasi     90    True    Male
2     Yaw   22      Tamale     78   False    Male
3  Akosua   24  Cape Coast     88    True  Female
4   Kwame   27          Ho     92    True    Male
5   Abena   23    Takoradi     80   False  Female
6    Kojo   26     Sunyani     87    True    Male

We use the `drop` feature in pandas to delete a column

In [14]:
dataF_ = dataF.copy()
dataF_.drop(columns=['Gender'])

     Name  Age        City  Score  Passed
0     Ama   20       Accra     85    True
1    Kofi   25      Kumasi     90    True
2     Yaw   22      Tamale     78   False
3  Akosua   24  Cape Coast     88    True
4   Kwame   27          Ho     92    True
5   Abena   23    Takoradi     80   False
6    Kojo   26     Sunyani     87    True

In [15]:
dataF_ = dataF.copy()
dataF_.drop(['Gender'],axis=1)

     Name  Age        City  Score  Passed
0     Ama   20       Accra     85    True
1    Kofi   25      Kumasi     90    True
2     Yaw   22      Tamale     78   False
3  Akosua   24  Cape Coast     88    True
4   Kwame   27          Ho     92    True
5   Abena   23    Takoradi     80   False
6    Kojo   26     Sunyani     87    True

### 4.3. ILOC VRS LOC

iloc and loc support columns selections and filtering for specific regions on the dataset.

iloc → Position-based selection

Uses integer positions (like Python lists)
You select by row number and column number

understanding ILOC

`df1.iloc[row, column]`


loc → Label-based selection

Uses column names and index labels
You can also use conditions

Examples
1. Select the first row and 2nd column

In [17]:
df.iloc[0,1]

np.int64(20)

2. Selection the first 4 rows across all columns

In [ ]:
df.iloc[:4, :]

     Name  Age        City  Score  Passed  Gender
0     Ama   20       Accra     85    True  Female
1    Kofi   25      Kumasi     90    True    Male
2     Yaw   22      Tamale     78   False    Male
3  Akosua   24  Cape Coast     88    True  Female

#### Task 3

a. Select the first two rows and the last 2 columns

b. Selection the last row and the last column

c. select the third column

In [ ]:
#IMPLEMENTATION
result1 = df1.________
result2 = df1.________
result3 = df1.________

NameError: name 'df1' is not defined

In [ ]:
#@title ▶️ Check if answer is correct
def check_answer(result1, result2, result3):
    expected1 = df1.iloc[:2, -2:]
    expected2 = df1.iloc[-1, -1]
    expected3 = df1.iloc[:, 1]

    try:
        assert result1.equals(expected1), "result1 is incorrect"
        assert result2 == expected2, "result2 is incorrect"
        assert result3.equals(expected3), "result3 is incorrect"
        print("Correct! All outputs match exactly.")
    except AssertionError as e:
        print(f"Incorrect: {e}")

check_answer(result1, result2, result3)

NameError: name 'result1' is not defined

4.3.1. LOC

To better understand LOC we would used it on the example

`df2  = pd.DataFrame(data2, columns=['Name','DayofBirth','Gender'], index=['first','Second','Third','Fourth','fifth'])`

In [30]:
df2

          Name DayofBirth Gender
first    Adwoa     Monday     Fm
Second    Kofi     Friday     Ma
Third    Abena    Tuesday     Fm
Fourth     Esi     Sunday     Fm
fifth   Joakim        NaN     Ma

In [29]:
df2.loc['Second','Name']

'Kofi'

In [31]:
df2.loc['first':'fifth','Name']

first      Adwoa
Second      Kofi
Third      Abena
Fourth       Esi
fifth     Joakim
Name: Name, dtype: object

In [32]:
df2.loc['first':'fifth','Name':'Gender']

          Name DayofBirth Gender
first    Adwoa     Monday     Fm
Second    Kofi     Friday     Ma
Third    Abena    Tuesday     Fm
Fourth     Esi     Sunday     Fm
fifth   Joakim        NaN     Ma

If a dataset has no predefined index, pandas assigns a default integer index (0, 1, 2, ...). These values act as index labels, so they can be used with .loc.

Example

In [ ]:
df1.loc[0:2,"Name"]

#### Task 4

a. Select the first two rows and the last 2 columns

b. Selection the last row and the last column

c. select the third column

In [ ]:
df1

In [ ]:
#IMPLEMENTATION
result1 = df1.________
result2 = df1.________
result3 = df1.________

In [ ]:
#@title ▶️ Check if answer is correct
def check_answer(result1, result2, result3):
    expected1 = df1.loc[0:1,'DayofBirth':'Gender']
    expected2 = df1.loc[4,'Gender']
    expected3 = df1.loc[:,'DayofBirth']

    try:
        assert result1.equals(expected1), "result1 is incorrect"
        assert result2 == expected2, "result2 is incorrect"
        assert result3.equals(expected3), "result3 is incorrect"
        print("Correct! All outputs match exactly.")
    except AssertionError as e:
        print(f"Incorrect: {e}")

check_answer(result1, result2, result3)

NameError: name 'result1' is not defined

### 4.4. Conditional Selection and Filtering in Pandas

In pandas, conditional selection is used to filter rows or columns based on specific conditions.

#### Common Operators

* `==` → Equal to
* `>` → Greater than
* `<` → Less than
* `>=`, `<=` → Greater/Less than or equal to

#### Combining Conditions

* `&` → Logical **AND** (both conditions must be true)
* `|` → Logical **OR** (at least one condition must be true)

> Always wrap each condition in parentheses when using `&` or `|`.

In [ ]:
df1.Name == "Adwoa"

0     True
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

In [ ]:
df1.loc[df1.Gender == 'Fm']

    Name DayofBirth Gender
0  Adwoa     Monday     Fm
2  Abena    Tuesday     Fm
3    Esi     Sunday     Fm

In [ ]:
df1.loc[(df1.Name == 'Adwoa') & (df1.Gender== 'Fm')]

    Name DayofBirth Gender
0  Adwoa     Monday     Fm

In [ ]:
df1.loc[(df1.Name == 'Adwoa') | (df1.Gender== 'Fm')]

    Name DayofBirth Gender
0  Adwoa     Monday     Fm
2  Abena    Tuesday     Fm
3    Esi     Sunday     Fm

<!-- ### Groupby and Sorting

in data preparation, your model would like to train/ test entities with specific features with unique charactertistics.

Pandas has functions called groupby and sorting

Groupby is a function that allows one sort data across a selected feature(column) as well as compare and extract data with another columns. The function has the features below that help provided further information on selected areas
min()

max()

count() -->

### 4.5. GroupBy in Pandas

In data preparation for machine learning, each row represents a unique entity (e.g., a student, customer, or observation) with specific features (columns).

Sometimes, we want to analyze or transform data based on shared characteristics.  
For example, grouping all students with the same name or all samples from the same class.

In groupby, the column you group by becomes the index of the result, not the original rows.

Pandas provides the `groupby()` function to support this.

### What is `groupby()`?

`groupby()` is used to group rows in a dataset based on the values of one or more columns.

It follows a three-step process:
1. **Split** the data into groups based on a column (e.g., "Name")
2. **Apply** a function to each group
3. **Combine** the results into a new structure

---

### Example

```python
df.groupby("Name")["Score"].mean()

In [36]:
import pandas as pd

data = {
    "Name": ["Ama", "Kofi", "Ama", "Yaw", "Kofi"],
    "City": ["Accra", "Kumasi", "Accra", "Tamale", "Kumasi"],
    "Score": [80, 75, 90, 60, 85]
}

df_group = pd.DataFrame(data)
print(df_group)

   Name    City  Score
0   Ama   Accra     80
1  Kofi  Kumasi     75
2   Ama   Accra     90
3   Yaw  Tamale     60
4  Kofi  Kumasi     85

In [37]:
df_group.groupby('Name')

from the code above  `df_group.groupby('Name')`

The dataframe is grouped as:

Ama →

   ` Name   City   Score`

    Ama    Accra  80

    Ama    Accra  90


Kofi →

    Name   City   Score

    Kofi   Kumasi 75

    Kofi   Kumasi 85


Yaw →
    Name   City   Score

    Yaw    Tamale 60

In [38]:
df_group.groupby('Name').Score.min()

Name
Ama     80
Kofi    75
Yaw     60
Name: Score, dtype: int64

In [39]:
df_group.groupby('Name').Score.max()

Name
Ama     90
Kofi    85
Yaw     60
Name: Score, dtype: int64

In [40]:
df_group.groupby('Name').Score.mean()

Name
Ama     85.0
Kofi    80.0
Yaw     60.0
Name: Score, dtype: float64


`apply():` lets you run a custom function on each group, where each group is treated as a mini DataFrame. It is flexible and can return a single value, a Series, or even a DataFrame.

`transform():` method allows you to execute a function for each value of the DataFrame.


`agg():` Is used to compute summary statistics for each group, often reducing each group to a single value per function such as min, max

In [42]:
df_group

   Name    City  Score
0   Ama   Accra     80
1  Kofi  Kumasi     75
2   Ama   Accra     90
3   Yaw  Tamale     60
4  Kofi  Kumasi     85

In [47]:
# used to impact the elements within a column in the dataset

df_group.groupby('Name').apply(lambda a: a.Score.iloc[-1])

/tmp/ipykernel_1895/1388277865.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_group.groupby('Name').apply(lambda a: a.Score.iloc[-1])

Name
Ama     90
Kofi    85
Yaw     60
dtype: int64

In [48]:
df_group.groupby('Name').Score.agg(['min','max','mean'])

      min  max  mean
Name
Ama    80   90  85.0
Kofi   75   85  80.0
Yaw    60   60  60.0

#### Sort

`df_group.sort_values(by='Name')`
In the example above, Name is considered as the index for the dataframe

In [49]:
df_group.sort_values(by='City')

   Name    City  Score
0   Ama   Accra     80
2   Ama   Accra     90
1  Kofi  Kumasi     75
4  Kofi  Kumasi     85
3   Yaw  Tamale     60

### save df to csv file

## 5. Removing duplicates
In data preprocessing, In addition to NaN values, the provided data may have duplicates. That is repeated values accross several rows.

For effective data, these duplicates need to be removed. Pandas has a built in function called `drop_duplicates()`.

`drop_duplicates()` function remove duplicate values across rows. 

The function takes these parameters:

`DataFrame.drop_duplicates(subset=None, *, keep='first', inplace=False, ignore_index=False)`

More information on these parameters can be accessed here `https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html`

In [110]:
ds = pd.read_csv("ethnicity_age_data.csv") 
ds_dup= ds.copy() # making a copy of the original dataset 
print(ds.shape)
ds_dup.drop_duplicates(inplace=True)
print(ds_dup.shape)

(213, 3)
(157, 3)

Can you explain why the shape for ds_dup and ds_nodup is different from the second implementation

In [111]:
ds_dup= ds.copy() # making a copy of the original dataset 
print(ds.shape)
ds_nodup= ds_dup.drop_duplicates()
print(ds_dup.shape)
print(ds_nodup.shape)

(213, 3)
(213, 3)
(157, 3)

In data preparation, the data is not always clean, therefore removing duplicates might not be straight forward as information in data may have grammatical errors or have different case, such as either capslock or lowercase. 

In the exercise below, we would be learning how to remove duplicates by first analyzing dataset and creating efficient functions to remove duplicate.

In [112]:
# hide this code 

ds = pd.read_csv("ethnicity_age_data.csv") 
ds_modified = ds.copy()

for i in range(100):
   num = random.randint(0,len(ds['Ethnicity'])-1)

   ethnic = ds.loc[num,'Ethnicity']

   if pd.notna(ethnic):
      ds_modified.loc[num,'Ethnicity'] = ethnic.upper()

In [113]:
#what can you observe in the dataframe under the column Ethnicity.
ds_modified

       Age  Ethnicity Country
0     16.0        Ada   Ghana
1     20.0       AKAM   Ghana
2      NaN       AKAN   Ghana
3     27.0       Akan   Ghana
4     28.0       AKAN   Ghana
..     ...        ...     ...
208  100.0  Voltarian  Canada
209   23.0       Wala   Ghana
210   31.0    WANGARA   Ghana
211   70.0    Zabarma   Ghana
212   28.0   Zambrema   Ghana

[213 rows x 3 columns]

In [114]:
#create a function that get rid of duplicates 

print(ds_modified.head())
def remove_duplicate(ds):
    for i in range(len(ds)):
        ethnic = ds_modified.loc[i,'Ethnicity']
        if pd.notna(ethnic):
             ds_modified.loc[i,'Ethnicity'] = ds_modified.loc[i,'Ethnicity'].lower()
    print(ds_modified.head())
    ds_modified.drop_duplicates(inplace=True)
    return ds_modified

    Age Ethnicity Country
0  16.0       Ada   Ghana
1  20.0      AKAM   Ghana
2   NaN      AKAN   Ghana
3  27.0      Akan   Ghana
4  28.0      AKAN   Ghana

In [115]:
remove_duplicate(ds_modified)
print(ds_modified.shape)

    Age Ethnicity Country
0  16.0       ada   Ghana
1  20.0      akam   Ghana
2   NaN      akan   Ghana
3  27.0      akan   Ghana
4  28.0      akan   Ghana
(155, 3)

If we observe the dataset clearly, there appears to mispelt names for certain ethnic groups.

The task is to write function that corrects the mistakes and remove the duplicates.

In [116]:
#Implement


## Mini Project: *Analyzing House Rentals in Ghana*

### Background

You are given a dataset containing house rental listings from Ghana. The dataset includes information such as price, number of bedrooms, location, and whether the house is furnished.

Your task is to use **pandas** to explore and analyze the dataset to uncover useful insights.

### Tasks
These tasks are guidance to answer the questions in Task 9, you can skip some of these tasks and manipulate the dataset to answer the questions in task 9

### Task 1: Load and Inspect the Data

* Load the dataset into a pandas DataFrame house_rentals.csv
* Display the first 5 rows
* Check the data types of each column

In [118]:
import pandas as pd


### Task 2: Data Selection

* Select the following columns:

  * `price`, `bedrooms`, `bathrooms`, `locality`, `region`, `is_furnished`
* Create a new DataFrame with only these columns

### Task 3: Data Cleaning

* Remove rows with missing values
* Confirm that the dataset has no null values

### Task 4: Filtering

* Find all houses with **more than 2 bedrooms**
* Find all **furnished houses**
* Find houses that cost **more than 3000**

*Use .apply() in this task*

### Task 5: Feature Engineering (apply)

Create a new column called **`price_category`**:

* "Low" → price < 1000
* "Medium" → price between 1000 and 3000
* "High" → price > 3000


### Task 6: GroupBy Analysis

* Calculate the **average price per region**
* Calculate the **average price per number of bedrooms**

### Task 7: Aggregation

For each region, compute:

* minimum price
* maximum price
* average price

### Task 8: Using the Transform function

* Normalize the price within each region using:
  
$$ \frac{x - \text{mean}}{\text{std}} $$

### Task 9: Insights

Answer the following questions:

1. Which region has the highest average rent?
2. Do houses with more bedrooms cost more on average?
3. Are furnished houses generally more expensive?
4. Which price category is the most common?